Just to get an idea, I was  trying to code the concept described in the article - https://pub.towardsai.net/building-neural-networks-from-scratch-with-python-code-and-math-in-detail-i-536fae5d7bbf

I used the code given in the article as my reference.

In [2]:
## libraries
import numpy as np

In [7]:
## inputs
inputs = np.array([[0,0], [1,1], [1,0], [0,1], [1,2], [2,1], [1,3], [3,1]])
inputs

array([[0, 0],
       [1, 1],
       [1, 0],
       [0, 1],
       [1, 2],
       [2, 1],
       [1, 3],
       [3, 1]])

In [6]:
inputs.shape

(8, 2)

In [9]:
## target outputs

target_op = np.array([0,1,1,2,0,1,2,1])

## reshaping the target outputs
target_op = target_op.reshape(8, 1)

target_op

array([[0],
       [1],
       [1],
       [2],
       [0],
       [1],
       [2],
       [1]])

In [10]:
weights = np.array([[0.6], [0.1]])

weights

array([[0.6],
       [0.1]])

In [11]:
bias = 0.45

## learning rate
lr = 0.01

In [12]:
## activation function

def sigmoid(x):
  return 1/(1+np.exp(-x))

In [13]:
## derivative of the activation function
## with respect to x
def del_sigmoid(x):
  return sigmoid(x)*(1-sigmoid(x))

In [17]:
## running the code "n" times

n = 10000

for epoch in range(n):

  ## feedforward inputs
  in_o = np.dot(inputs, weights) + bias

  ## feedforward output
  out_o = sigmoid(in_o)

  ## backpropagation process starts here
  ## finding error (simple error function for simplicity in the calculation)
  error = out_o - target_op

  error_sum = error.sum()

  ## 1st derivative
  delerror_del_op = error

  ## 2nd derivative
  delop_delip = sigmoid(out_o)
  ## multiplying both 1st and 2nd derivative
  deriv = delerror_del_op*delop_delip

  input_new = inputs.T
  deriv_final = np.dot(input_new, deriv)

  ## updating weights
  weights -= lr* deriv_final
  
  ## updating bias
  for i in deriv:
    bias = bias - lr*i




In [18]:
print(weights)
print(bias)

[[  1.61489229]
 [146.65700226]]
[4.68161327]


In [20]:
single_pt = np.array([1,0])

result1 = np.dot(single_pt, weights) + bias

result2 = sigmoid(result1)

print(result2)

[0.99816066]
