Iris dataset is used


In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [4]:
iris = load_iris()

In [5]:
print("Classes: ", iris.target_names)

Classes:  ['setosa' 'versicolor' 'virginica']


In [7]:
## data attributes

x = iris.data

## target labels

y = iris.target

In [10]:
type(x), type(y), x.shape, y.shape

(numpy.ndarray, numpy.ndarray, (150, 4), (150,))

In [13]:
print(x[:2]) 

print("-------------------")
print(y[:2])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]]
-------------------
[0 0]


In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 20, test_size = 0.25)

In [15]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [20]:
x_test[:10], y_test[:10]

(array([[4.6, 3.2, 1.4, 0.2],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [7.2, 3. , 5.8, 1.6],
        [5.8, 2.7, 4.1, 1. ],
        [5.5, 2.5, 4. , 1.3],
        [6.8, 3.2, 5.9, 2.3],
        [5.1, 3.7, 1.5, 0.4],
        [6.7, 2.5, 5.8, 1.8],
        [4.8, 3. , 1.4, 0.1]]), array([0, 1, 1, 2, 1, 1, 2, 0, 2, 0]))

In [21]:
x_train[:10], y_train[:10]

(array([[6.4, 3.2, 4.5, 1.5],
        [7.4, 2.8, 6.1, 1.9],
        [5.7, 2.8, 4.5, 1.3],
        [6.1, 2.6, 5.6, 1.4],
        [4.9, 3.6, 1.4, 0.1],
        [6.7, 3.1, 4.4, 1.4],
        [6.3, 3.3, 4.7, 1.6],
        [4.7, 3.2, 1.3, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [5. , 3.3, 1.4, 0.2]]), array([1, 2, 1, 2, 0, 1, 1, 0, 0, 0]))

In [22]:
## decision tree classifier
classfier = DecisionTreeClassifier(criterion= "entropy")

In [23]:
## training
classfier.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [24]:
## predicting the labels

y_predict = classfier.predict(x_test)

In [28]:
## evaluation metric (accuracy)

from sklearn.metrics import accuracy_score

print("for train data, accuracy: ", accuracy_score(y_true = y_train, y_pred = classfier.predict(x_train)) )

print("for test data, accuracy: ", accuracy_score(y_true = y_test, y_pred = y_predict) )

for train data, accuracy:  1.0
for test data, accuracy:  0.9210526315789473


## Experimenting

By changing the parameters.
Documentation - [https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html)


In [30]:
########        Changing min_sample_split

## decision tree classifier
classfier = DecisionTreeClassifier(criterion= "entropy", min_samples_split=50)

## training
classfier.fit(x_train, y_train)

## predicting the labels
y_predict = classfier.predict(x_test)

## evaluation metric (accuracy)
print("for train data, accuracy: ", accuracy_score(y_true = y_train, y_pred = classfier.predict(x_train)) )

print("for test data, accuracy: ", accuracy_score(y_true = y_test, y_pred = y_predict) )

for train data, accuracy:  0.9821428571428571
for test data, accuracy:  0.8947368421052632


In [32]:
########        Changing min_sample_split

## decision tree classifier
classfier = DecisionTreeClassifier(criterion= "entropy", min_samples_split=10)

## training
classfier.fit(x_train, y_train)

## predicting the labels
y_predict = classfier.predict(x_test)

## evaluation metric (accuracy)
print("for train data, accuracy: ", accuracy_score(y_true = y_train, y_pred = classfier.predict(x_train)) )

print("for test data, accuracy: ", accuracy_score(y_true = y_test, y_pred = y_predict) )

for train data, accuracy:  0.9910714285714286
for test data, accuracy:  0.9210526315789473
